### ISSUE TITLE
Plugin crash when launched without KeeTheme

### ISSUE THREAD

**Issue by ikeblaster** [CennoxX/KeePass-QuickSearch#1]
Steps to replicate
1. Download fresh KeePass (https://sourceforge.net/projects/keepass/files/KeePass%202.x/2.57/KeePass-2.57.zip/download)
2. Add QuickSearch.pglx (https://github.com/CennoxX/KeePass-QuickSearch/releases/download/2.38/QuickSearch.plgx)
3. Launch

Error message appears during startup.

Workaround:
1. Add KeeTheme
3. Launch KeePass
4. Enable and then disable Dark Theme
5. (optional) Remove KeeTheme
6. Restart KeePass

**Comment by ikeblaster** [comment]
I think it crashes here (null pointer), not sure.
https://github.com/CennoxX/KeePass-QuickSearch/blob/acf83734c1692f42bb42c072cc57782a8b8451ce/QuickSearch/QuickSearchControl.cs#L65

**Comment by CennoxX** [comment]
Thanks for the detailed issue. This is fixed with 2.39.
