### ISSUE TITLE
Shortcut CTRL-E handling when minimized

### ISSUE THREAD

**Issue by ikeblaster** [CennoxX/KeePass-QuickSearch#3]
Currently this plugin captures CTRL-E shortcut globally, so it doesn't work in other application. It probably should be handled only when KeePass is in focus.

**Comment by CennoxX** [comment]
Can you test the build at the bottom of https://github.com/CennoxX/KeePass-QuickSearch/actions/runs/11175188606?

**Comment by ikeblaster** [comment]
@CennoxX Better, but sadly I found one situation where it still doesn't work. This might be tricky to reproduce. Windows 10, taskbar with "combine taskbar buttons: never". When I minimize KeePass by clicking on the taskbar button, the shortcut is still captured. I assume the `Deactivate` event is not called when it's minimized in this specific way, for some strange reason.

Some ideas (but I'm rather rusty in C#/winforms):
- Checking `host.MainWindow.ContainsFocus()` in the hook.
- Listening to `host.MainWindow.KeyDown` instead of the lowlevel hook (though I think this won't work well enough).
- In some other event checking if the KeePass window is minimized.

I might look into it myself, eventually (I just don't have VS installed at this moment).

**Comment by CennoxX** [comment]
@ikeblaster `host.MainWindow.ContainsFocus` seems to do the trick, but I don't have Windows 10 around to test...
Can you test the build https://github.com/CennoxX/KeePass-QuickSearch/actions/runs/11201172896?

**Comment by ikeblaster** [comment]
@CennoxX Quickly tested, it seems to be perfect now. Thank you very much and have a nice day! :)

**Comment by CennoxX** [comment]
This will be included in the next release.
