### ISSUE TITLE
Title show User Name after Field Edit

### ISSUE THREAD

**Issue by geva-kf-admin** [CennoxX/keepass-quicksearch#6]
Problem: The value User Name will also show in the column Title after some Field Edit.

STR:
1. Use QuickSearch and found some entries.
2. Edit one found entry.
3. Now the column Title shows the User Name if it was filled. If it is not filled the output is `<TAN>`

Screenshot Step 1:
![capt_003](https://github.com/user-attachments/assets/17f0fc49-ee68-4baf-be4a-7f6142fdee86)

Screenshot Step 3:
![capt_004](https://github.com/user-attachments/assets/f56c75a0-0ce1-44b4-a371-8da0cd6f375a)

**Comment by CennoxX** [comment]
I can't reproduce this.
How do you get the column "Mail", is this made via Edit Entry > Advanced > String fields or via plugin? Do you have other plugins installed?
`<TAN>` is the default title of a TAN entry (Tools > TAN Wizard)
Can you recreate this in a minimal database?
